# Generated by Django 5.0.3 on 2024-11-18 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_made_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER')], default='MANAGER', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=200)),
                ('workshop_date', models.DateTimeField(blank=True, null=True)),
                ('workshop_description', models.TextField(blank=True, null=True)),
                ('workshop_logo', models.ImageField(upload_to='logo/')),
                ('workshop_location', models.CharField(max_length=500)),
                ('workshop_seats', models.IntegerField(blank=True, null=True)),
                ('workshop_tables', models.IntegerField(blank=True, null=True)),
                ('number_workshop_groups', models.IntegerField(blank=True, null=True)),
                ('workshop_seats_per_table', models.IntegerField(blank=True, null=True)),
                ('workshop_uuid', models.UUIDField(default=uuid.uuid4)),
                ('is_closed', models.BooleanField(default=False)),
                ('workshop_manager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=500)),
                ('tables', models.CharField(max_length=1000)),
                ('workshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=500)),
                ('alloted_table', models.CharField(blank=True, max_length=50, null=True)),
                ('alloted_group', models.CharField(blank=True, max_length=100, null=True)),
                ('is_visited', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('WorkshopVisitors_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('workshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workshop')),
            ],
        ),
    ]
