# Generated by Django 5.0.3 on 2024-11-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='workshop_date',
        ),
        migrations.AddField(
            model_name='workshop',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='photos_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
