# Generated by Django 5.0.3 on 2024-11-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_workshop_workshop_date_workshop_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='photos_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
