# Generated by Django 5.0.3 on 2024-11-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_workshop_photos_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
