# Generated by Django 5.0.3 on 2024-11-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_workshop_workshop_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
