# Generated by Django 5.0.3 on 2024-11-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_workshop_workshop_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopvisitors',
            name='name',
        ),
        migrations.AddField(
            model_name='workshopvisitors',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workshopvisitors',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workshopvisitors',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workshopvisitors',
            name='participating_as',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workshopvisitors',
            name='designation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
