# Generated by Django 5.0.3 on 2024-11-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_workshopvisitors_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
    ]
