# Generated by Django 5.0.3 on 2024-11-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
