# Generated by Django 5.0.3 on 2024-12-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_feedback_email_remove_feedback_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopvisitors',
            name='participating_as',
        ),
        migrations.AddField(
            model_name='workshopvisitors',
            name='is_presenter',
            field=models.BooleanField(default=False),
        ),
    ]
