# Generated by Django 5.0.3 on 2024-12-06 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_workshopvisitors_participating_as_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop_designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=500)),
                ('designation_tables', models.CharField(max_length=1000)),
                ('workshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workshop')),
            ],
        ),
    ]
