# Generated by Django 5.0.3 on 2024-12-06 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_workshop_designations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop_designations',
            name='workshop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='main.workshop'),
        ),
        migrations.AlterField(
            model_name='workshopvisitors',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workshop_designations'),
        ),
    ]
