# Generated by Django 5.0.3 on 2024-12-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_workshop_designations_workshop_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopvisitors',
            name='designation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
