# Generated by Django 5.0.3 on 2024-12-06 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_workshopvisitors_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopvisitors',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workshop_designations'),
        ),
    ]
