# Generated by Django 5.0.3 on 2024-12-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_workshopvisitors_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=255)),
                ('question_2', models.CharField(max_length=255)),
                ('question_3', models.CharField(max_length=255)),
                ('question_4', models.CharField(max_length=255)),
                ('question_5', models.CharField(max_length=255)),
                ('question_6', models.CharField(max_length=255)),
                ('question_7', models.CharField(max_length=255)),
                ('question_8', models.CharField(max_length=255)),
                ('question_9', models.CharField(max_length=255)),
            ],
        ),
    ]
