# Generated by Django 5.0.3 on 2024-12-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_feedback_comments_remove_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='presenter_tables',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
