# Generated by Django 5.0.3 on 2024-12-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_workshop_presenter_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_designation_required',
            field=models.BooleanField(default=True),
        ),
    ]
