# Generated by Django 5.0.3 on 2024-12-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_workshop_is_designation_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop_designations',
            name='workshop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='main.workshop'),
        ),
    ]
