# Generated by Django 5.0.3 on 2024-12-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_workshop_designations_workshop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopvisitors',
            name='designation_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
