# Generated by Django 5.0.3 on 2024-12-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_workshopvisitors_designation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopvisitors',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workshop_designations'),
        ),
    ]
