# Generated by Django 5.2.10 on 2026-03-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_workshopvisitors_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
